UTILSDIR := utils/args

$(OBJDIR)/hpy_args.o: $(UTILSDIR)/hpy_args.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_options.o: $(UTILSDIR)/hpy_options.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_option_error.o: $(UTILSDIR)/hpy_option_error.cc
	$(CC) $(CFLAGS) -c -o $@ $<



