COREDIR := core

$(OBJDIR)/hpy_proxy.o: $(COREDIR)/hpy_proxy.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_handler.o: $(COREDIR)/hpy_handler.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_httpmessage.o: $(COREDIR)/hpy_httpmessage.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_encryption.o: $(COREDIR)/hpy_encryption.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_decryption.o: $(COREDIR)/hpy_decryption.cc
	$(CC) $(CFLAGS) -c -o $@ $<


