COREDIR := core

$(OBJDIR)/hpy_proxy.o: $(COREDIR)/hpy_proxy.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_handler.o: $(COREDIR)/hpy_handler.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_connection.o: $(COREDIR)/hpy_connection.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/hpy_tcp.o: $(COREDIR)/hpy_tcp.cc
	$(CC) $(CFLAGS) -c -o $@ $<

